### PR TITLE
Hello Microverse Project

### PR DESCRIPTION
**Pull request by julie-ify**
## Hello Microverse Project.

In this project I:
- Set up linter and fixed linter errors
- Added index.html file and style.css file
- Added header to the index.html file 
- Added styles to the header

### CODE REVIEW

**Comment by mikenath223** [comment]
Hi @julie-ify 

You made a great effort in this project, but unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that will be invalidated for this reason:
- Follow the exact instructions [here](https://github.com/microverseinc/linters-config/tree/master/html-css) and include all linters config files for Webhint and Stylelint.
- Update the readme with Getting started instructions.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Happy coding. Cheers!🚀🚀

If something isn't 100% clear, you can leave comments or questions in this PR thread.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, whether valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **don't count** into the code reviews limit._

**Comment by julie-ify** [comment]
Hello,
Please do you mean I should not put the linters config files for Webhint and Stylelint in .gitignore file?

**Comment by mikenath223** [comment]
> Hello,
> Please do you mean I should not put the linters config files for Webhint and Stylelint in .gitignore file?

Yea. Kindly include them in the commit.

**Comment by julie-ify** [comment]
OK thanks

**Review by carlos-ssh — CHANGES_REQUESTED** [review]
Hi @julie-ify , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
**- It's needed a README file with full information about your project.**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by julie-ify** [comment]
OK, Thanks

**Comment by julie-ify** [comment]
I have commited the README.md file as requested.
Please check it out.
Thanks

**Review by abruzy — CHANGES_REQUESTED** [review]
Hi @julie-ify  👏 , 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Required Changes! ♻️ 
_1. Kindly check the comments under the review._
_2. Let's make your repo looks professional by applying one of the  5 professional repo basic rules, kindly update your `README` file.
Checkout out the below link for help, feel free to follow this [template](https://github.com/microverseinc/readme-template) from pathwright_

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by mikenath223 — APPROVED** [review]
Hello @julie-ify,  

Your project is complete!  There is nothing else to say other than... it's time to merge it 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the PR thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
